version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/voting-app-backend
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  db_data: