version: "3.9"
services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"
  api:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/voting-app
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - api-redis:/var/lib/redis/data
  sidekiq:
    build:
      context: .
    command: bundle exec sidekiq
    volumes:
      - '.:/voting-app'
    working_dir: /voting-app
    links:
      - db
      - redis
    env_file:
      - .env
  # appsmith:
  #   image: index.docker.io/appsmith/appsmith-ce
  #   container_name: appsmith
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "9001:9001"
  #   volumes:
  #     - ./stacks:/appsmith-stacks
  #   labels:
  #     com.centurylinklabs.watchtower.enable: "true"
  #   restart: unless-stopped
  # auto_update:
  #   image: containrrr/watchtower:latest-dev
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --schedule "0 0 * ? * *" --label-enable --cleanup
  #   restart: unless-stopped
volumes:
  db_data:
  api-redis: