version: "3.9"
services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ".env"
  api:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/voting-app
    env_file:
      - ".env"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
  redis:
    image: redis:7.0
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - api-redis:/var/lib/redis/data
  sidekiq:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    restart: always
    command: bundle exec sidekiq
    volumes:
      - '.:/voting-app'
    working_dir: /voting-app
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
volumes:
  db_data:
  api-redis: