development:
  adapter: postgresql
  encoding: unicode
  host: db
  database: voting_app_development
  pool: 5
  username: voting_app
  password: voting_app

test:
  adapter: postgresql
  encoding: unicode
  host: db
  database: voting_app_test
  pool: 5
  username: voting_app
  password: voting_app