development:
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV.fetch("POSTGRES_HOST") %>"
  database: "<%= ENV.fetch("POSTGRES_DB_DEV") %>"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") %>"
  username: "<%= ENV.fetch("POSTGRES_USER") %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") %>"

test:
  adapter: postgresql
  encoding: unicode
  host: "<%= ENV.fetch("POSTGRES_HOST") %>"
  database: "<%= ENV.fetch("POSTGRES_DB_TEST") %>"
  pool: "<%= ENV.fetch("RAILS_MAX_THREADS") %>"
  username: "<%= ENV.fetch("POSTGRES_USER") %>"
  password: "<%= ENV.fetch("POSTGRES_PASSWORD") %>"